name: CMake build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Install Protobuf
        run: sudo apt-get install protobuf-compiler

      - name: Configure and Build Project
        uses: threeal/cmake-action@main

      # run simple example as a test
      - name: Build and run example
        run: |
          cd example/simple
          cmake --build .
          ./simple
